apiVersion: v1
kind: ConfigMap
metadata:
  name: mm-fortend-config
  namespace: marketmandu-ns
data:
  apiURL: http://108.129.186.179.nip.io/server
  PAYMENT_BACKEND_URL: http://payment-svc.marketmandu-ns.svc.cluster.local:3009/api/v1
  esewa_url: https://rc-epay.esewa.com.np/api/epay/main/v2/form
  esewa_secret: 8gBm/:&EnhH.1/q
  CLOUDFRONT_DOMAIN: https://d1l8ti7xj3tpl6.cloudfront.net/